### ISSUE TITLE
Getting Approval on Topic

### ISSUE THREAD

**Issue by CryogenicPlanet** [CryogenicPlanet/Cisco-internship#1]
**We need to work on meeting the principal and getting approval on a project idea so we can start working.**

## Proposal 1.Bus BarCode Scanner  
In brief, this concept would allow us to scan our id card to get on the school bus which would solve two problems, First being the long 10 15 mins the dispersal assembly takes which could be eliminated all together by making all students scan their id card before boarding the buses to ensure no one is left behind, This software will be programmed to handle ELP stay backs and students who use different routes in the morning and evening along with a provision to add special exceptions. The Second problem this would solve is to be an easy check for who all have paid the transport fees and using school transport without paying for it.

## Proposal 2.Online Lending Library  
This project involves the sharing of books amongst people in a community or area, for the pilot, run it will be only in the school. This services will allow users to add the extra books they might have at home and be willing to lend to other, they will also have access to the books added by other and they could find this by searching for the book they want. Once they find a book they want they can use our service to communicate with each other to set a time and place to meet up and exchange books. (For the pilot this will be available only to school students and all meets and exchanges will have within school campus for safety reasons)
This would be a great platform for reading enthusiasts to find and exchange new books and get an opportunity to read new books at no cost whatsoever.

**Comment by LaserTrajectory** [comment]
Is this the gist of the proposal you sent to Sai sir? If so, good because it's quite informative.

**Comment by CryogenicPlanet** [comment]
@LaserTrajectory That is the whole proposal I sent but the proposals were meant to be a gist we are to explain them in depth during our meeting on Wednesday.
