### ISSUE TITLE
Finalising Our Idea

### ISSUE THREAD

**Issue by CryogenicPlanet** [CryogenicPlanet/Cisco-internship#2]
#1 From That We Can mostly say we are doing project two unless anyone has a specific objection please comment right now.

I would like to start talking about the specificity of the project and assigns individuals to certain parts and tasks of the project.

- [ ] Choose Scope of Application

- [ ] Choose What Platforms this Application would be one

- [ ] Choose The Technologies Needed to Achieve This(Including Languages we will be using)

- [ ]  Study Each Individuals Team member's strengths and weaknesses to see what our team can do.

- [ ] Do a full feasibility study of the application in question

- [ ] Dividing and Assigning Work to certain parts of the project.

- [ ]  Construct a Timeline for the project and assign milestones we need to meet

**Comment by popxxisjustaflower** [comment]
What should I do, senpai?
((It was a compliment btw...))
